name: minjie
favicon: null
layout_spectrum: 0.43812286271713674
typography_spectrum: 0.7575896682683378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4476113507989794
  lightness: 0.2301303434651345
  saturation: 0.06733533111400902
  rhythmicContrast: 0.23500890471041203
purpose: []
